# Generated by Django 4.2 on 2023-04-26 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_schedule_created_at_alter_schedule_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='user',
        ),
    ]
